const INVENTORY_REASON_CODES = Object.freeze([
  'INITIAL_STOCK',
  'MANUAL_RECEIPT',
  'MANUAL_USAGE',
  'PHYSICAL_COUNT',
  'MANUAL_CORRECTION',
  'RECIPE_COOK',
  'WASTE_SPOILAGE',
  'WASTE_EXPIRED',
  'WASTE_PREP',
  'WASTE_DAMAGE',
  'WASTE_OTHER',
])

const WASTE_REASON_CODES = Object.freeze([
  'WASTE_SPOILAGE',
  'WASTE_EXPIRED',
  'WASTE_PREP',
  'WASTE_DAMAGE',
  'WASTE_OTHER',
])

const WASTE_REASON_LABELS = Object.freeze({
  WASTE_SPOILAGE: 'Spoilage',
  WASTE_EXPIRED: 'Expired',
  WASTE_PREP: 'Prep waste',
  WASTE_DAMAGE: 'Damage',
  WASTE_OTHER: 'Other',
})

const CONSUMPTION_REASON_CODES = Object.freeze(['MANUAL_USAGE', 'RECIPE_COOK'])

module.exports = {
  INVENTORY_REASON_CODES,
  WASTE_REASON_CODES,
  WASTE_REASON_LABELS,
  CONSUMPTION_REASON_CODES,
}
